version: '3'
services:
    mongo:
        image: mongo:latest
        ports:
          - "27017:27017"
        restart: always
        environment:
              - MONGO_INITDB_DATABASE=Storage
    invmanage:
      image: invmanage:1.0
      links:
        - mongo
      depends_on:
        - mongo
      ports:
       - "8000:8000"


